### ISSUE TITLE
getting a MIFARE_Write() failed: A MIFARE PICC responded with NAK

### ISSUE THREAD

**Issue by orlax** [konstantin-kelemen/arduino-amiibo-tools#2]
Hey there, thank you for creating these tools, i am currently using a  MIFARE Ultralight Ntag215 to create my amiibo cards, the issue is that when trying to write to the card i get the error: 

 MIFARE_Write() failed: A MIFARE PICC responded with NAK

and after that every attemp to write to the card is just a time out communication error. 

an initial search tells me the error is because i need to authenticate before writing to the card as ther state in this [link](http://stackoverflow.com/questions/26719509/mfrc522-picc-responded-with-nak-porting-mfrc522-arduino-libraryc-to-c)

however i dont see any use of the mfrc522.PCD_Authenticate() function in your code, maybe this was not necessary for the tags you used? 

i am trying to figure out were would i need to put the authentication part on the code but thruth is a need help. 

thank you.

**Comment by konstantin-kelemen** [comment]
Hi, @orlax 

No, you don't need to authenticate while writing to a blank tag.

The error you mentioned usually appears when you're writing to a used tag which already has a password set.

Just take another tag and write the dump to it.

**Comment by orlax** [comment]
that`s the thing, i am writing to a brand new tag i just received, i will try to write to another tag, however does that means i can no longer used the tag that throws the error? this things cost me like 3 bucks a piece so i would like very much being able to re-use them.

**Comment by konstantin-kelemen** [comment]
I have never had issues with new tags. They don't have password set so there is no need to authenticate.

Tags also don't usually cost that much. Have never seen tags which cost more than $0.70 a piece (incl. shipping).

You may check, maybe you still have a chance to rescue your "locked" tags.

In order todo so use the Dump_amiibo sketch and check that Dynamic and Static Lock Bytes are set to zero. Check [this datasheet](https://www.nxp.com/documents/data_sheet/NTAG213_215_216.pdf) in order to find the bytes to look at.

You should also know the password and acknowledge phrase to unlock the tag and to be able to write to it again in case the Lock Bytes are OK. Check the Ntag216_AUTH sketch that comes with MFRC522 library for a nice example.

**Comment by orlax** [comment]
thank you, i will look into this, i live in colombia so yeah tags here are quite expensive (could order from china directly but that would take months to arrive thouthg) maybe if i find a solution i will fork the library. 

be well.

**Comment by konstantin-kelemen** [comment]
Good luck and happy cloning! 🐑 🐑
