### ISSUE TITLE
Card reuse

### ISSUE THREAD

**Issue by alwlsek** [konstantin-kelemen/arduino-amiibo-tools#8]
Hi,

Thank you for a good explanation.

There are some questions to ask you.
When creating such a dump file using uid and bin files, I would like to know the interaction between them.
Then I would like to make offline and know the way of reusing the card if available.

Please, check and kindly advise asap.
Waiting for your response.

Have a nice day.

**Comment by konstantin-kelemen** [comment]
Hi @alwlsek 
You can check [this post](https://gbatemp.net/threads/making-amiibo-ntag215s.413050/) where the dump modification process is described in detail.

Also you cannot reuse a tag once amiibo has been written to it since the tag becomes locked in the process. This is a requirement for the amiibo cards.
